spring:
  profiles:
    active: dev
#配置环境





family:
  family-name: "happy family"
  father: "Jack"
  mother: "Rose"
  child: "Tom"
  years: 30




person:
  name: zhangsan
  age: 20
  happy: false
  birthday: 2001/07/08
  maps: {k1:v1,k2:v2}
  lists:
    -code
    -girl
    -music
  dog:
    name: 虎子
    age: 11